### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by trevordmiller** [apple/swift-org-website#228]
## Is your feature request related to a problem? Please describe

I'd like to be notified when there are new posts at https://www.swift.org/blog/. The footer currently has a feed icon which links to `https://www.swift.org/atom.xml`. However, the tools I use only support RSS, not Atom. So I am not currently able to subscribe.

<img width="178" alt="image" src="https://user-images.githubusercontent.com/5497885/215848894-e42ccd18-bc5d-41e6-bc9e-deb1d521cd38.png">

## Describe the solution you'd like

Please add an additional RSS feed to go along with the current Atom feed for RSS users.

## Describe alternatives you've considered

I've considered using an Atom to RSS converter service, but would prefer to subscribe directly and officially at the source.

## Additional context

I'm not familiar with the implementation details so I might be wrong, but perhaps this could be implemented by adding another front matter option like the current `atom: true`?

https://github.com/apple/swift-org-website/blob/105bb8ca5cf1a0162061c5b92556178976fdc105/blog/index.html#L4

**Comment by ishaanbedi** [comment]
> I assume a similar one has to be created for RSS: 

As per my understanding, the go-to way is to create a /feed.rss file in the folder or a feed.xml file but with RSS syntax.
I'd like to contribute by creating such a file and changing the specified code with valid RSS snippets.
Can I start working on it?

**Comment by MaxDesiatov** [comment]
I don't see why not. You may also need to add references to the new file, similarly to how `atom.xml` is already linked in a few places: https://github.com/apple/swift-org-website/search?q=atom.xml

**Comment by daveverwer** [comment]
Before diving into a fix for this, I’d love to chat a little more about the best solution.

@trevordmiller I’d love to understand more about the issue you’re having. It’s been a while since I came across anything that would accept Atom and not RSS (or vice versa). I don’t doubt there’s an issue, but I’m curious what the software is.

I also checked whether the feed was valid in case that was causing a problem. There are a [couple of minor issues](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.swift.org%2Fatom.xml) but nothing significant.

Then, it’s also not 100% clear to me what we should do to fix the issue. We could implement both types of feed, but that has downsides, too. People would need to choose what feed to subscribe to when adding it to a reader, and there’s also additional maintenance overhead with a custom feed.

The alternative is to just change the type of feed at the same URL. I’m not a big fan of that idea, though. I think most feed readers would cope with it, but you know software! 😬 It would also feel strange having RSS content in a file named `atom.xml`.

As an aside. `jekyll-feed` only supports Atom, and an RSS feed would need to be a custom template. There’s some discussion on why Jekyll chose Atom [here](https://github.com/jekyll/jekyll-feed#why-atom-and-not-rss), for context.

@ishaanbedi I’d hold off just for a short while until we decide what to do to fix the issue.

**Comment by bflagg** [comment]
I have been dogged by certain http clients not dealing correctly with the feed's content-encoding.

For example:
```
curl -LO "https://www.swift.org/atom.xml"
file ./atom.xml 
./atom.xml: gzip compressed data, max speed, from Unix, original size modulo 2^32 1883500

```

**Comment by trevordmiller** [comment]
> @trevordmiller I’d love to understand more about the issue you’re having. It’s been a while since I came across anything that would accept Atom and not RSS (or vice versa). I don’t doubt there’s an issue, but I’m curious what the software is.

@daveverwer My use case is that my team at work would like to subscribe to official Swift blog posts within our team chat so we can stay up-to-date and discuss them together. The chat software we are required to use within our organization is Microsoft Teams. The supported option is [the official RSS connector](https://learn.microsoft.com/en-us/connectors/rss/). It works with other feeds we use. For example, [Apple Developer News](https://developer.apple.com/news/) at `https://developer.apple.com/news/rss/news.rss`. But `https://www.swift.org/atom.xml` gives an error:

<img width="248" alt="image" src="https://user-images.githubusercontent.com/5497885/216712145-d9fbe2c5-b05e-4ba8-8ba4-ea5987be657e.png">

I completely understand the desire to not add complexity or custom solutions if the tradeoffs are not worth it. Especially if this is an uncommon situation specific to Microsoft Teams. If that is the case we can close the issue no worries :) I really appreciate everyone's time and the additional information!

**Comment by daveverwer** [comment]
> @daveverwer My use case is that my team at work would like to subscribe to official Swift blog posts within our team chat so we can stay up-to-date and discuss them together. The chat software we are required to use within our organization is Microsoft Teams. The supported option is [the official RSS connector](https://learn.microsoft.com/en-us/connectors/rss/). It works with other feeds we use. For example, [Apple Developer News](https://developer.apple.com/news/) at `https://developer.apple.com/news/rss/news.rss`. But `https://www.swift.org/atom.xml` gives an error:

Thanks so much for the additional context, that's interesting. We'll discuss this at the next workgroup meeting and make a decision on how to proceed.

**Comment by kaishin** [comment]
> I have been dogged by certain http clients not dealing correctly with the feed's content-encoding.
> 
> For example:
> 
> ```
> curl -LO "https://www.swift.org/atom.xml"
> file ./atom.xml 
> ./atom.xml: gzip compressed data, max speed, from Unix, original size modulo 2^32 1883500
> ```

@bflagg To help with investigating this issue, is it possible to share an example of a client that doesn't support gzip compression?

**Comment by daveverwer** [comment]
We had a discussion of this at the workgroup meeting tonight and concluded that we don't think adding an additional feed is the best way forward. If there are specific issues with the encoding then we'd be happy to look at that in more detail, but would suggest a new issue for that.
