### ISSUE TITLE
Website markdown does not render C++ code blocks with C++ highlighting

### ISSUE THREAD

**Issue by hyp** [apple/swift-org-website#305]
While working on https://github.com/apple/swift-org-website/pull/299, I noticed that the markdown code I added to represent a C++ sample, is not rendered with C++ highlighting on my local instance on the website.

Please support specifying a language like C++ in the code blocks, using Github's syntax, e.g.:

```
```c++
```

**Comment by ishaanbedi** [comment]
Hey @alexandersandberg!

I'd like to work on this issue.

As you suggested that some classes are missing from the scss file. The approach I'd like to follow is to explicitly initialize the classes and their corresponding styling effects for those classes exclusive to CPP (such as `.nl`) that haven't been initialized in the scss file yet but are present in cpp code blocks across the website. 

There are 44 such instances of `"```c++"` code blocks and 1 instance for `"```cpp"`, and most of the classes are common & overlap with each other among these instances, so manual scanning and working on them would not be a difficult task.

I don't have much experience using [rouge](https://github.com/rouge-ruby/rouge), but I had a quick glance at the repo and could not find any information about CPP classes or styling instructions, if they provide. If you could help me by letting me know the best way to proceed, I would highly appreciate it.

— @ishaanbedi

**Comment by alexandersandberg** [comment]
Thanks for wanting to help out, @ishaanbedi!

IIRC the problem here is that there's no theme provided by rouge that matches the theme we use on the website, so it's not as simple as copy-pasting over the missing values from somewhere.

Instead, we might have to look at existing rouge themes to see how the individual colors are distributed across different classes and try to replicate those patterns to our theme. 

However, this color distribution might differ between themes, so we also need to do some trial and error here to in the end make the C++ syntax match the rest of the website's syntax.

I think it would be great to set up a little test page (temporarily, which will be removed later) with a few code snippets in C++ and maybe one or two other languages that contain as many syntax highlighting classes as possible. This can then be used while evaluating whether a color suits a certain class or not.

Does that make sense?

**Comment by ishaanbedi** [comment]
Hi @alexandersandberg !

That does sound right.

> Instead, we might have to look at existing rouge themes to see how the individual colors are distributed across different classes and try to replicate those patterns to our theme.

I was able to extract css files for the themes supported by rouge [here](https://github.com/ishaanbedi/rouge-extracted-css) and I can see it has various classes which are not declared in the `_syntax.scss` file for the website, so yeah I can get references from inspecting them and comparing what all is missing, and replicating them based on the theming styles and guidelines of the website as per the theming and colors for other code blocks, just like you mentioned.

Also, this website https://spsarolkar.github.io/rouge-theme-preview/ does provide a great overview about pre-existing rouge themes, so I can get help from this as well.

> I think it would be great to set up a little test page (temporarily, which will be removed later) with a few code snippets in C++ and maybe one or two other languages that contain as many syntax highlighting classes as possible. This can then be used while evaluating whether a color suits a certain class or not.

Sounds great, I'd like to give it a shot. For this, I'll open a draft PR while pushing commits on the go, since this will require deployments so as to see the colors and theming.

**Comment by alexandersandberg** [comment]
Perfect, thank you!

> Sounds great, I'd like to give it a shot. For this, I'll open a draft PR while pushing commits on the go, since this will require deployments so as to see the colors and theming.

Sadly, we're still in the process of setting up preview deployments for PRs, but you should be able to run the website locally and see the changes there.

**Comment by ishaanbedi** [comment]
> Sadly, we're still in the process of setting up preview deployments for PRs, but you should be able to run the website locally and see the changes there.

Oh, okay! I have set up the website environment locally and deployed it over here: https://swift-org-website.ishaanbedi.in/

Also, I have created an example page as you suggested: https://swift-org-website.ishaanbedi.in/issue305, and I have added a code example across C++, Swift & JS, to compare and work on the classes over there.

I'll keep you updated about the changes or progress I'll be making!

**Comment by ishaanbedi** [comment]
Hi @alexandersandberg !

I was able to make some progress with the issue, and so far, it looks like:
| Before    | After |
| -------- | ------- |
| <img width="313" alt="" src="https://github.com/apple/swift-org-website/assets/39641326/e3d4c7fc-adad-4930-a428-2ec5c6565404"> |  <img width="249" alt="" src="https://github.com/apple/swift-org-website/assets/39641326/22aec73e-e25f-4405-ad73-8542ea50e332"> |
|  <img width="501" alt="" src="https://github.com/apple/swift-org-website/assets/39641326/21706846-abcc-4a87-a5e0-53220e363825"> |  <img width="489" alt="" src="https://github.com/apple/swift-org-website/assets/39641326/7f912ca3-e032-4aa8-87ca-f11cfff8fb81"> |

I tried my best to match the theming of these blocks with the rest of the website and compared Swift & JS code blocks side by side for the same. 

You can have a look at it here: https://swift-org-website.ishaanbedi.in/issue305
Or compare side by side between examples at: https://www.swift.org/documentation/cxx-interop/ & https://swift-org-website.ishaanbedi.in/documentation/cxx-interop/

I would like to know your feedback on this, or any suggestions you might have.

**Comment by alexandersandberg** [comment]
This looks like a great improvement already! Feel free to open a draft PR and I can take a closer look at the changes and see if I have any suggestions for further improvement. 🙂

**Comment by ishaanbedi** [comment]
Hi @alexandersandberg !
I've opened a draft PR as per your suggestion [here](https://github.com/apple/swift-org-website/pull/463).

**Comment by federicobucchi** [comment]
This has been merged.  Closing.
