### ISSUE TITLE
In getting-started/_build-system.md "Building an Executable,"   a main.swift file is referenced.

### ISSUE THREAD

**Issue by johan718** [apple/swift-org-website#333]
## Describe the bug

In getting-started/_build-system.md "Building an Executable,"   a main.swift file is referenced. My swift package command does not create a `main.swift` file. It is still creating a `hello.swift` file and it is still an executable program. Is the documentation out of date or is this a new feature?

I am using Swift 5.7.2. Was this changed in later versions?

## To Reproduce

Run the following commands in a terminal window:
1. mkdir hello
2. cd hello
3. swift package init --type executable

Now, inspect your `hello/Sources/hello` directory.

## Expected behavior

According to the documentation, [Using the Package Manager](https://www.swift.org/getting-started/#using-the-package-manager), there should be a `main.swift` file in the `Sources/hello` directory.

## Actual behavior

There is only `hello.swift` in the `Sources/hello` directory.

### Desktop (please complete the following information):

- Device: Macbook Pro M1 2021
- OS: Ventura 13.4
- Swift Version: 5.7.2

**Comment by 0xTim** [comment]
@johan718 the page is out of date. Most executables now use `@main` to mark the entry point, though main.swift is still valid. Fancy doing a PR?

**Comment by natikgadzhi** [comment]
@0xTim, hi there! I would love to help clean this up. 

Do you think just updating the article to how things work with 5.8 / 5.9 is a reasonable step, or should we somehow link to how it worked in previous versions of Swift, so that folks that navigate to that guide, but have a previous version of the toolchain, won't get confused?

**Comment by 0xTim** [comment]
@natikgadzhi I think updating for the current version of Swift is valid

**Comment by natikgadzhi** [comment]
@0xTim, thanks for the guidance! After a bit of digging, it seems like there are significant changes to the getting started guide in #354. And `getting-started/cli-swiftpm/index.md` in https://github.com/apple/swift-org-website/pull/354/files#diff-3aff12dcb3b420a97ef3e3788541bbd61caee1d33a12408b7f39fcf46df96f8bR1 is the new guide on how to bootstrap a CLI app with Swift Package Manager. #354 is pretty huge, but it solves this issue once it's merged.

I _think_ it would be better to get #354 in faster, rather than patch the existing guide one-off — that would only make more merge conflicts for us. 

How can I best help move it forward? (I'll go ask there as well ;-) )

**Comment by tomerd** [comment]
@natikgadzhi we plan to merge #354 pretty soon. you can wait until we do, or feel free to create PRs against the `content-improvments` branch which has all these changes and anything merged there will roll into #354

**Comment by natikgadzhi** [comment]
The new guide in `content-improvements` is already pretty good, and up to date — so I unless I miss more context (which I might), it'll be more than enough to close this issue.

As far as swift-org-website work, I'll get those broken links cleaned up, and then work to add tags to the blog (#98).
