### ISSUE TITLE
Display links to author mastodon/twitter

### ISSUE THREAD

**Issue by rauhul** [apple/swift-org-website#477]
The authors yaml file currently has a twitter field that doesn't appear in the swift.org UI anywhere (as far as I can tell). It would be nice to display this information as a clickable icon and include support for mastodon profiles

**Comment by dempseyatgithub** [comment]
After discussion, the website workgroup decided that instead of adding links to multiple profiles per author across multiple services, the site will use only GitHub profile links for author profiles.

A more detailed explanation of the decision is in the closed PR:
https://github.com/apple/swift-org-website/pull/481#issuecomment-1919731807
